### ISSUE TITLE
Problem inserting a graph in calc

### ISSUE THREAD

**Issue by quelo1972** [CollaboraOnline/Docker-CODE#27] opened 2018-04-29 21:16 UTC
I have ubuntu-server 16.04 LTS with nextcloud installed and working, I installed the docker image of collabora code and work with nextcloud.
But when I insert a graph in calc and click on "Save" I have the error below:
![cattura](https://user-images.githubusercontent.com/28729838/39411064-f7574db2-4c02-11e8-90e4-ae64f5877246.PNG)
translated from the italian "Unable to save document to storage space. Check your permissions or contact the storage server administrator."

What's the problem?

**Comment by quelo1972** [comment] 2018-04-30 13:02
In the docker log I have the following ERR when I click on "Save":

`
mwsd-00026-00041 12:59:46.806779 [ docbroker_001 ] ERR  Cannot save docKey [/nextcloud/apps/richdocuments/wopi/files/1664_ocvfyj3y2l3m], the .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:758`

**Comment by quelo1972** [comment] 2018-05-04 18:55
Is there anyone that tryed to reproduce and then solve the problem?

**Comment by s-john19** [comment] 2018-05-08 10:48
I tried to reproduce it but for me its working without any problem. Do you have any error in the nextcloud log when you get this?

**Comment by quelo1972** [comment] 2018-05-08 12:04
In the docker container I have the following error:

mwsd-00026-00041 12:59:46.806779 [ docbroker_001 ] ERR Cannot save docKey [/nextcloud/apps/richdocuments/wopi/files/1664_ocvfyj3y2l3m], the .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:758

Where is the nextcloud log?

**Comment by s-john19** [comment] 2018-05-08 12:08
In the Nextcloud settings -> logs. You need to be admin to see them of course.

**Comment by quelo1972** [comment] 2018-05-08 15:57
No errors in nextcloud log.

**Comment by s-john19** [comment] 2018-05-09 17:42
When you go to the about screen, which version do you see? I mean the about screen of collabora online.

**Comment by quelo1972** [comment] 2018-05-09 18:26
I don't use any kind of encryption... I think... How can I verify this with certainty?
Unfortunately I'm not very expert with docker. How can I update the collabora image without re-download it?

**Comment by s-john19** [comment] 2018-05-09 18:28
You can't update it without re-download. You need to pull the latest image:
docker pull collabora/code

Then you need to stop and rm your current container (you can find the id with docker ps):
docker ps
docker stop ID
docker rm ID

And then youi can start collabora again like you do it every time:
docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=cloud\.nextcloud\.com' --restart always --cap-add MKNOD collabora/code


And just go to your nextcloud settings - do you see there any encryption option in the sidebar?

**Comment by s-john19** [comment] 2018-05-09 18:30
But I have an idea:
How did you installed your nextcloud installation? Which "tutorial" did you use?

**Comment by quelo1972** [comment] 2018-05-09 18:34
I used the following tutorial
`https://bayton.org/docs/nextcloud/installing-nextcloud-on-ubuntu-16-04-lts-with-redis-apcu-ssl-apache/`

**Comment by s-john19** [comment] 2018-05-09 18:36
Can you go to the /nextcloud/apps/richdocuments/wopi/files directory and type "ls -l" and paste the result here?

**Comment by quelo1972** [comment] 2018-05-09 18:38
`root@DROP02:/var/www/html/nextcloud/apps/richdocuments# cd /var/www/html/nextcloud/apps/richdocuments/wopi/files
-bash: cd: /var/www/html/nextcloud/apps/richdocuments/wopi/files: File o directory non esistente`

**Comment by s-john19** [comment] 2018-05-09 18:40
yeah and there please type in "ls -l" as far as it works. And btw - your collabora app in nextcloud is also up to date? YOURWEBSITE.tld/settings/apps?category=enabled#

**Comment by quelo1972** [comment] 2018-05-09 18:44
The directory `/var/www/html/nextcloud/apps/richdocuments/wopi/files` doesn't exists!
the version of collabora code app in nextcloud is
![cattura](https://user-images.githubusercontent.com/28729838/39833204-b3ee4976-53c9-11e8-8193-932774198d43.PNG)

**Comment by s-john19** [comment] 2018-05-09 18:46
Then please use ls -l in the /var/www/html/nextcloud/apps/richdocuments/wopi or /var/www/html/nextcloud/apps/richdocuments/wopi/wopi dictionary. I want to check the file permissions.

**Comment by quelo1972** [comment] 2018-05-09 18:48
there is not any wopi dir as you can see below
```
root@DROP02:/var/www/html/nextcloud/apps/richdocuments# ls -la
totale 52
drwxr-xr-x 10 www-data www-data 4096 mag  4 16:22 .
drwxr-xr-x 57 www-data www-data 4096 mag  7 19:49 ..
drwxr-xr-x  2 www-data www-data 4096 mag  4 16:22 appinfo
drwxr-xr-x  2 www-data www-data 4096 mag  4 16:22 assets
-rw-r--r--  1 www-data www-data 2121 mag  4 16:22 CHANGELOG.md
drwxr-xr-x  3 www-data www-data 4096 mag  4 16:22 css
drwxr-xr-x  2 www-data www-data 4096 mag  4 16:22 img
-rw-r--r--  1 www-data www-data 3124 mag  4 16:22 issue_template.md
drwxr-xr-x  3 www-data www-data 4096 mag  4 16:22 js
drwxr-xr-x  2 www-data www-data 4096 mag  4 16:22 l10n
drwxr-xr-x  7 www-data www-data 4096 mag  4 16:22 lib
-rw-r--r--  1 www-data www-data 2786 mag  4 16:22 README.md
drwxr-xr-x  2 www-data www-data 4096 mag  4 16:22 templates
root@DROP02:/var/www/html/nextcloud/apps/richdocuments#
```

**Comment by thebearon** [comment] 2018-05-09 18:54
Indeed, the save failes with a chart in the spreadsheet, but only if you click save. Closing the file triggers an automatic save, which succeeds (provided no manual save was attempted beforehand).

**Comment by quelo1972** [comment] 2018-05-09 18:58
@thebearon 
now I can't try this because I'm downloading the latest docker image of collabora/code

**Comment by quelo1972** [comment] 2018-05-09 19:27
@s-john19 

> Do you use any kind of encryption in nextcloud?
And btw can you do me a favor? Can you pull the latest docker image of CODE and go into languages? Do you still see the dictionaries (DE, IT, EN, ..)?

![cattura](https://user-images.githubusercontent.com/28729838/39835189-ae022bee-53cf-11e8-9936-059cd26cd231.PNG)
Why I don't have anymore the languages? Before I have it!!!

**Comment by s-john19** [comment] 2018-05-09 19:31
@quelo1972 Its because of the new version pushed to the docker hub.
Which languages do you need? I can give you the copy and paste lines to get them back. I just wanted to know if it's a bug only for me, because it was working for others.

**Comment by quelo1972** [comment] 2018-05-09 19:33
I need Italian and english how can I add them?

**Comment by quelo1972** [comment] 2018-05-09 19:35
@s-john19 @thebearon 
have you any idea to the save problem? Why for me the automatic saving doesn't work? How doesn't work clicking on save button and the document isn't saved when there is a chart in the spreadsheet?

**Comment by s-john19** [comment] 2018-05-09 19:37
Ok here are the lines:
docker ps to see the new name of the container (it should be the last one, a random name you can also take the container id)

docker exec -it IDorNAME bash

And then:
mkdir -p /usr/share/hunspell
mkdir -p /usr/share/hyphen
mkdir -p /usr/share/mythes
mkdir -p /opt/lool/systemplate/usr/share/hyphen

for i in `find /opt/collaboraoffice5.3/share/extensions/ -name hyph*.dic`;do cp $i /opt/lool/systemplate/usr/share/hyphen;done
for i in `find /opt/collaboraoffice5.3/share/extensions/ -name hyph*.dic`;do cp $i /usr/share/hyphen;done

for it:
cp /opt/collaboraoffice5.3/share/extensions/dict-it/it_IT.* /usr/share/hunspell
cp /opt/collaboraoffice5.3/share/extensions/dict-it/th_it_IT_v2.dat /usr/share/mythes
cp /opt/collaboraoffice5.3/share/extensions/dict-it/th_it_IT_v2.idx /usr/share/mythes

for en_US:
cp /opt/collaboraoffice5.3/share/extensions/dict-en/en_US.* /usr/share/hunspell
cp /opt/collaboraoffice5.3/share/extensions/dict-en/th_en_US_v2.dat /usr/share/mythes
cp /opt/collaboraoffice5.3/share/extensions/dict-en/th_en_US_v2.idx /usr/share/mythes

**Comment by quelo1972** [comment] 2018-05-09 19:37
The problem is there also if I use libreoffice/online docker image instead collabora/code!!!

**Comment by s-john19** [comment] 2018-05-09 19:42
@quelo1972 and about the auto save: Try to create a new spreadsheet, add something to it, click on the normal save button, add a chart - wait 5 minutes - click on x of collabora online.

It could be a problem of a slow internet connection.

**Comment by s-john19** [comment] 2018-05-09 19:44
@quelo1972 and thank you, now I know its not just me where the dictionaries are not showing up without the lines. 

Please confirm here if you see the dictionaries again and if auto save is working with the waittime :)

**Comment by quelo1972** [comment] 2018-05-09 19:46
@s-john19 
```
root@216f75ca2275:/# for i in find /opt/collaboraoffice5.3/share/extensions/ -name hyph*.dic;do cp $i /opt/lool/systemplate/ue/hyphen;done
cp: cannot stat 'find': No such file or directory
cp: omitting directory '/opt/collaboraoffice5.3/share/extensions/'
cp: invalid option -- 'm'
Try 'cp --help' for more information.
cp: cannot stat 'hyph*.dic': No such file or directory
```

**Comment by s-john19** [comment] 2018-05-09 19:49
@quelo1972 Just copy the hole line, in your line there is an mistype "/opt/lool/systemplate/ue/hyphen" instead of "/opt/lool/systemplate/usr/share/hyphen;done" - in putty you can paste things with right click.

**Comment by quelo1972** [comment] 2018-05-09 19:52
@s-john19 

```
root@216f75ca2275:/# for i in find /opt/collaboraoffice5.3/share/extensions/ -name hyph*.dic;do cp $i /opt/lool/systemplate/un;donee
cp: cannot stat 'find': No such file or directory
cp: omitting directory '/opt/collaboraoffice5.3/share/extensions/'
cp: invalid option -- 'm'
Try 'cp --help' for more information.
cp: cannot stat 'hyph*.dic': No such file or directory
```

**Comment by s-john19** [comment] 2018-05-09 19:59
@quelo1972 A new docker image is out now where dictionaries are working again. If you still have problems with my lines you can download it again, but it should work without any problem with my lines.

**Comment by quelo1972** [comment] 2018-05-09 21:06
No, wait for 5 minutes didn't work for me, after click to Red X button the spreadsheet is closed but the chart is not saved.
I re pull the docker image and Now I nave the languages. But the "save" button still return the error when a chart is present.

**Comment by s-john19** [comment] 2018-05-09 21:10
@quelo1972 Great that you have the dictionaries again. About auto save - do you see anything in the logs of collabora? For me its working.
I created a test sheet -> Added a chart -> clicked on the x -> got back to the document and the chart was still there. 

But now they know about the bug, that the save button is not working - so it should get fixed

**Comment by quelo1972** [comment] 2018-05-09 21:14
Where is the logs of collabora?

**Comment by timar** [comment] 2018-05-23 08:04
Version 3.2.2 was released 12 days ago, have not you pulled it? It was a bugfix release. In the previous version, the explicit save using the toolbar button could fail with .odf files containing charts.  Other formats like .xls or .xlsx, and auto-saving of .odf were not affected. 

The CODE docker images now contain all the available dictionaries and thesauri. A new environment variable can be set to specify the appropriate subset of languages to be used at runtime. See also: https://www.collaboraoffice.com/code/

**Closed by timar** 2018-05-23 08:04 UTC
Labels: bug

**Comment by quelo1972** [comment] 2018-05-23 09:20
For me still doesn't work!
I've removed container and the image and the pulled the the new image and started container.

Still I have error after saving a spreadsheet containing a chart!

**Comment by quelo1972** [comment] 2018-05-23 09:33
@timar 
In fact the version is not 3.2.2 but 3.2.0 as you can see below
![cattura](https://user-images.githubusercontent.com/28729838/40416220-0b544f22-5e7d-11e8-8b31-a4b39b9ce334.PNG)

**Comment by timar** [comment] 2018-05-23 09:49
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
collabora/code                      latest              d5900995e7eb        12 days ago         1.54GB

loolforkit version details: 3.2.2 - ffc419a

**Comment by quelo1972** [comment] 2018-05-23 10:08
Excuse me but I'm not a docker expert (I'm newbye!) how can I pull this image?
I have done 
```
docker pull collabora/code
docker run -t -i -d -p 127.0.0.1:9980:9980 -e 'domain=drop\.ddns\.net' --restart unless-stopped --cap-add MKNOD collabora/code
```

**Comment by quelo1972** [comment] 2018-05-23 10:35
excuse me I was wrong!!! Now the version is right...
![cattura](https://user-images.githubusercontent.com/28729838/40419206-dfef96fe-5e84-11e8-9215-8a4c265faf1c.PNG)
But the saving a spreadsheet containing a chart still doesn't work!!!
![cattura](https://user-images.githubusercontent.com/28729838/40419455-b0d290aa-5e85-11e8-8571-2bcbd403812d.PNG)

**Comment by quelo1972** [comment] 2018-05-24 08:16
Can you re-open the issue please?

**Comment by quelo1972** [comment] 2018-06-04 14:21
Can you reopen the issue? I still have this problem, is there anyone can help me to solve it?

Thanks.
