### ISSUE TITLE
Unable to generate launch Docker container

### ISSUE THREAD

**Issue by alchy58** [CollaboraOnline/Docker-CODE#18] opened 2017-09-17 08:02 UTC
Hi,
I juste tried to run collabora with Docker (as root and as non root) but got issues. I don't know why it's happens, maybe is it related to the generation of the SSL certificate ?

```
# docker logs e655238e7110
Generating RSA private key, 2048 bit long modulus
........................................................................................+++
....+++
e is 65537 (0x10001)
Generating RSA private key, 2048 bit long modulus
.......................................................................................+++
....................+++
e is 65537 (0x10001)
Signature ok
subject=/C=DE/ST=BW/L=Stuttgart/O=Dummy Authority/CN=localhost
Getting CA Private Key
wsd-00025-00025 18:25:57.221773 [ loolwsd ] ERR  Failed to write to pipe. Data: [setconfig limit_virt_mem_mb 0
setconfig limit_stack_mem_kb 8000
setconfig limit_file_size_mb 50
]. (errno: Bad file descriptor)| common/IoUtil.cpp:200
frk-00027-00027 18:25:57.239603 [ forkit ] ERR  Failed to set RLIMIT_NOFILE to 52428800 bytes. (errno: Operation not permitted)| common/Seccomp.cpp:273
loolforkit version details: 2.1.3 - 277d2b8
wsd-00025-00025 18:26:47.227775 [ loolwsd ] FTL  Failed to fork child processes.| wsd/LOOLWSD.cpp:2563
FATAL: Failed to fork child processes.
wsd-00025-00025 18:26:47.228590 [ loolwsd ] FTL  Failed to fork child processes.| wsd/LOOLWSD.cpp:2707
Failed to fork child processes.
wsd-00025-00025 18:26:47.229449 [ loolwsd ] WRN  Waking up dead poll thread [admin], started: false, finished: false| ./net/Socket.hpp:507
wsd-00025-00025 18:26:47.229813 [ loolwsd ] WRN  Waking up dead poll thread [admin], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.230602 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.230712 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.230814 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.230909 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.231022 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.231122 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.231684 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:507
<shutdown>-00025 18:26:47.231796 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:507
frk-00027-00027 18:26:47.233659 [ forkit ] FTL  Pipe closed.| common/IoUtil.cpp:309
```
I'm launching Docker inside a Xen domU.
Dom0 is on Debian Stretch 9.1 with Xen Hypervisor 4.8.1-1+deb9u1 amd64
DomU is on Debian Stretch 9.1 too.
Docker version is :
```
# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:58:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

I don't really used Docker before, so if you need more informations, please ask.

Thank you very much.

**Comment by thebearon** [comment] 2017-11-16 18:21
Duplicate of #10.

**Closed by thebearon** 2017-11-16 18:21 UTC
